-module(slacker_team).

-include("spec.hrl").

-export([logs/2, info/1, integration_logs/2]).


%% @doc Get the access logs for users on a team.
%%
%% Options can be:
%% count: number of items to return per page (default: 100)
%% page: page number of results to return (default: 1)
%%
-spec logs(Token :: string(), Options :: list()) -> http_response().
logs(Token, Options) ->
    slacker_request:send("team.accessLogs", [{"token", Token}], Options).

%% @doc Provides information about your team.
-spec info(Token :: string()) -> http_response().
info(Token) ->
    slacker_request:send("team.info", [{"token", Token}]).

%% @doc Get the access logs for users on a team.
%%
%% Options can be:
%% service_id: filter logs to this service
%% app_id: filter logs to this app
%% user: filter logs generated by this user’s actions
%% change_type: filter logs with this change type
%% count: number of items to return per page (default: 100)
%% page: page number of results to return (default: 1)
%%
-spec integration_logs(Token :: string(), Options :: list()) -> http_response().
integration_logs(Token, Options) ->
    slacker_request:send("team.integrationLogs", [{"token", Token}], Options).
